#Script to deploy on Render

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  build: 
  
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env: 
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}

    - uses: bounceapp/render-action@0.6.0
      with: 
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cgp9fi0u9tun42sbn5l0?key=HWJyg97IkqQ"
        retries: 20
        wait: 16000
        sleep: 30000
        
      - run: npm ci
      - run: npm test
      - run: node acceptance
