#Script to deploy on Render

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs: 
  build: 
  
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - uses: bounceapp/render-action@0.6.0
      with: 
        render-token: ${{secrets.RENDER_API_KEY}}
        github-tokent: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cgp9fi0u9tun42sbn5l0?key=HWJyg97IkqQ"
        retries: 20
        wait: 16000
        sleep: 30000
